{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Small example how to initialize and use the library"}]},{"type":"codeListing","syntax":"swift","code":["let accelera = Accelera(","    config: AcceleraConfig(","        token: \"Token\",","        url: \"https:\/\/flow2.accelera.ai\",","        userId: \"userId\"","    )",")","accelera.delegate = self","accelera.logEvent(string: \"{\\\"event\\\": \\\"some_event\\\"}\")","accelera.loadBanner()"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/accelera"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/accelera"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Accelera library"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"Accelera","title":"Accelera","symbolKind":"module","role":"collection","modules":[{"name":"Accelera"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/Accelera"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraDelegate"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraConfig"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraBannerType"]}],"references":{"doc://org.cocoapods.Accelera/documentation/Accelera":{"role":"collection","title":"Accelera","abstract":[{"type":"text","text":"Accelera library"}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera","kind":"symbol","type":"topic","url":"\/documentation\/accelera"},"doc://org.cocoapods.Accelera/documentation/Accelera/AcceleraVersionString":{"role":"symbol","title":"AcceleraVersionString","fragments":[{"kind":"identifier","text":"AcceleraVersionString"}],"abstract":[{"type":"text","text":"Project version string for Accelera."}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraVersionString","kind":"symbol","type":"topic","url":"\/documentation\/accelera\/acceleraversionstring"},"doc://org.cocoapods.Accelera/documentation/Accelera/AcceleraVersionNumber":{"role":"symbol","title":"AcceleraVersionNumber","fragments":[{"kind":"identifier","text":"AcceleraVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for Accelera."}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/accelera\/acceleraversionnumber"},"doc://org.cocoapods.Accelera/documentation/Accelera/AcceleraDelegate":{"role":"symbol","title":"AcceleraDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AcceleraDelegate"}],"abstract":[{"type":"text","text":"Delegate that informs about banner events"}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AcceleraDelegate"}],"url":"\/documentation\/accelera\/acceleradelegate"},"doc://org.cocoapods.Accelera/documentation/Accelera/AcceleraBannerType":{"role":"symbol","title":"AcceleraBannerType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AcceleraBannerType"}],"abstract":[{"type":"text","text":"Banner type"}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraBannerType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AcceleraBannerType"}],"url":"\/documentation\/accelera\/accelerabannertype"},"doc://org.cocoapods.Accelera/documentation/Accelera/Accelera":{"role":"symbol","title":"Accelera","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Accelera"}],"abstract":[{"type":"text","text":"Main library class"}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/Accelera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Accelera"}],"url":"\/documentation\/accelera\/accelera"},"doc://org.cocoapods.Accelera/documentation/Accelera/AcceleraConfig":{"role":"symbol","title":"AcceleraConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AcceleraConfig"}],"abstract":[{"type":"text","text":"Library configuration"}],"identifier":"doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AcceleraConfig"}],"url":"\/documentation\/accelera\/acceleraconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraVersionNumber","doc:\/\/org.cocoapods.Accelera\/documentation\/Accelera\/AcceleraVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}